### ISSUE TITLE
When is the release?

### ISSUE THREAD

**Issue by slaFFik** [nikolaposa/rate-limit-middleware#1]
I know, that this middleware is based on your other lib [nikolaposa/rate-limit](https://github.com/nikolaposa/rate-limit), which I wanted to use initially.
But then suddenly I found this newly created repo, so now I'm wondering when you do plan to release it (tag `1.0.0`)?

**Comment by nikolaposa** [comment]
Plan is to release it later today, as soon as I cope with problems configuring Travis CI for this repo.

**Comment by slaFFik** [comment]
Thank you for your reply!

By no means I wanted to push you to do that asap or anything like that, that's was just my curiosity.
