### ISSUE TITLE
PHP 8 Compatibility

### ISSUE THREAD

**Issue by skyrie** [nikolaposa/rate-limit-middleware#2]
Would it be possible to update this middleware with PHP 8 compatibility? Thanks!

**Comment by nikolaposa** [comment]
Sure, I can work on that these days, but also, contributions are welcome.

**Comment by nikolaposa** [comment]
PHP 8 support added in the newest release: https://github.com/nikolaposa/rate-limit-middleware/releases/tag/1.1.0
