### ISSUE TITLE
Questions about classes

### ISSUE THREAD

**Issue by AlexeyNaum** [nikolaposa/rate-limit-middleware#4]
Hi. I'm trying to use your library, but I have confused with your  'RateLimit\\LimitExceededRequestHandler', 'RateLimit\\CreatePostRateLimitMiddleware', 'RateLimit\\ApiRateLimitMiddleware' (// default limit exceeded handler; anonymous class is used only for the sake of simplicity of the example) classes. Could you please give more information, examples about these classes?? I don't understand what should be there. My best regards!

**Comment by nikolaposa** [comment]
Hi, things you are referring to are just names of services that represent different rate limiting strategies. So for example:
- `'RateLimit\\CreatePostRateLimitMiddleware'`: rate limit middleware that works only for this specific `post.create` route
- `'RateLimit\\ApiRateLimitMiddleware'`: rate limit middleware that covers API routes
- `'RateLimit\LimitExceededRequestHandler'`: default, fallback rate limit middleware that is called for any other endpoint in the app.

Does that help? Examples are perhaps too biased towards micro-frameworks such as Mezzio.
